services:
  - type: web
    name: tbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GLM_API_KEY
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: USERS
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
